apiVersion: batch/v1
kind: Job
metadata:
  name: blue
spec:
  template:
    spec:
      containers:
      - name: blue
        image: oioki/blue-docker
        env:
        - name: COLOR
          value: "blue"
      restartPolicy: Never
  backoffLimit: 2
